@echo off
echo Cleaning up previous processes...
taskkill /f /im java.exe 2>nul
echo Cleaning database files...
del data\fooddb.mv.db 2>nul
del data\fooddb.trace.db 2>nul
echo Starting Spring Boot application...
.\mvnw.cmd spring-boot:run